### ISSUE TITLE
ESP support tracking

### ISSUE THREAD

**Issue by DNedic** [ZigEmbeddedGroup/microzig#221]
This issue tracks the support status for ESP32 series Espressif SoCs and will be updated with new tasks continously:

- [x] [Add GPIO driver](https://github.com/ZigEmbeddedGroup/microzig/pull/216)
- [ ] Add UART driver
- [ ] Add support for the ESP32-C6
- [x] Interrupt support
- [ ] Add support for digital addressable RGB LEDs found on many devboards (WS2811 compatible)
- [x] Add support for the ESP-IDF Application Image Format
- [ ] Enable caches

**Comment by Grazfather** [comment]
#415 should knock off this one when it's ready.

> Add support for the ESP-IDF Application Image Format

**Comment by Grazfather** [comment]
We also need an i2c driver, and most of these, to follow our standard hal api, will need a time driver so that we can use deadlines, so I think the time device should be next.

Uart was done by @tact1m4n3 in #436

**Comment by tact1m4n3** [comment]
Interrupts can be checked 😄
